app = "zerowidth-redis"

[mounts]
  destination = "/data"
  source = "redis_server"

[env]
  MAXMEMORY_POLICY = "allkeys-lru"
  APPENDONLY = "yes"
  FLY_VM_MEMORY_MB = 256

[metrics]
  port = 9091
  path = "/metrics"

[build]
  image = "flyio/redis:6.2"

[[services]]
internal_port = 6379
protocol      = "tcp"

  [[services.ports]]
  port     = "16379"

  [[services.tcp_checks]]
  interval = 10000
  timeout  = 2000
